import type { Metadata } from "next";
import { Header } from "./components/header";
import { Footer } from "./components/footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "CINEVERSE - Encontre Seus Filmes Favoritos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <link rel="icon" href="/icon.png" type="image/x-icon" />
      <body  className="bg-neutral-950 text-white">
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
